// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetSourcePath(arg1) {
  return window['go']['main']['App']['GetSourcePath'](arg1);
}

export function ListFolder(arg1) {
  return window['go']['main']['App']['ListFolder'](arg1);
}

export function StartMigration(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartMigration'](arg1, arg2, arg3);
}

export function ValidateBackupRoot() {
  return window['go']['main']['App']['ValidateBackupRoot']();
}
