// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetConfig():Promise<main.ConfigView>;

export function GetSourcePath(arg1:string):Promise<string>;

export function ListFolder(arg1:string):Promise<Array<main.FolderEntry>>;

export function StartMigration(arg1:Array<string>,arg2:Record<string, Array<string>>,arg3:boolean):Promise<void>;
