// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseForFolder(arg1) {
  return window['go']['main']['App']['BrowseForFolder'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetSourcePath(arg1) {
  return window['go']['main']['App']['GetSourcePath'](arg1);
}

export function ListFolder(arg1) {
  return window['go']['main']['App']['ListFolder'](arg1);
}

export function PreflightCheck(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['PreflightCheck'](arg1, arg2, arg3, arg4);
}

export function ScanDrive(arg1) {
  return window['go']['main']['App']['ScanDrive'](arg1);
}

export function StartMigration(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['StartMigration'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ValidateBackupRoot() {
  return window['go']['main']['App']['ValidateBackupRoot']();
}
